---
resolver: lts-19.27
arch: x86_64
flags: {}
packages: ["."]
allow-newer: true
extra-deps:
  - containers-0.6.4.1
  - criterion-1.5.13.0
  - parseargs-0.2.0.9
  - random-1.2.1.1
  - random-strings-0.1.1.0
  - text-1.2.5.0
